### ISSUE TITLE
main文件编译不通过

### ISSUE THREAD

**Issue by Sophanatprime** [FvNCCR228/SCU_Beamer_Slide-demo#2]
下载该repo后，**第一次**编译main文件无法成功编译：
```
No file main.toc.
! Undefined control sequence.
\insertsubsectionendframe ...r@subsectionendframe 
                                                  
l.88 \subsection{研究现状}
```

增加
```
\def\beamer@subsectionendframe{2}
```
后即可成功编译。

猜测是 `beamerthemescu.sty` 第388行写错了？
https://github.com/FvNCCR228/SCU_Beamer_Slide-demo/blob/fb4bbdd33f097c9b0732d23701da09df1ed8c92b/beamerthemescu.sty#L387-L399

将 `\beamer@endframeofsubsection` 改为 `\beamer@subsectionendframe` 后可正常编译。

**Comment by FvNCCR228** [comment]
嗯，对写错了，改为subsectionendframe就可以了，下版本修复吧

**Comment by Alafun** [comment]
感谢

**Comment by Alafun** [comment]
好像还是不行，出现部分提示如下
```shell
LaTeX Warning: Citation '_ugc_2018' on page 26 undefined on input line 9.


LaTeX Warning: Citation '__2018' on page 26 undefined on input line 10.

)
Overfull \hbox (13.1042pt too wide) in paragraph at lines 428--428
[][][][]  

Overfull \hbox (1.03467pt too wide) has occurred while \output is active
 [][]|  
[26]
No file main.toc.

Overfull \hbox (13.1042pt too wide) in paragraph at lines 433--433
[][][][]  

Overfull \hbox (1.03467pt too wide) has occurred while \output is active
 [][]|  
[27] <a0,fr0> <a0,fr1> <a0,fr2> <a0,fr3> <a0,fr4> <a0,fr5> <a0,fr6> <a0,fr7>
<a0,fr8> <a0,fr9> <a0,fr10> <a0,fr11> <a0,fr12> <a0,fr13> <a0,fr14> <a0,fr15>
<a0,fr16> <a0,fr17> <a0,fr18> <a0,fr19> <a0,fr20> <a0,fr21> <a0,fr22>
<a0,fr23> <a0,fr24> <a0,fr25> <a0,fr26> <a0,fr27> <a0,fr28> <a0,fr29>
<a0,fr30> <a0,fr31> <a0,fr32> <a0,fr33> <a0,fr34> <a0,fr35> <a0,fr36>
<a0,fr37> <a0,fr38> <a0,fr39> <a0,fr40> <a0,fr41> <a0,fr42> <a0,fr43>
<a0,fr44> <a0,fr45> <a0,fr46> <a0,fr47> <a0,fr48> <a0,fr49> <a0,fr50>
<a0,fr51> <a0,fr52> <a0,fr53> <a0,fr54> <a0,fr55> <a0,fr56> <a0,fr57>
<a0,fr58> <a0,fr59> <a0,fr60> <a0,fr61> <a0,fr62> <a0,fr63> <a0,fr64>
<a0,fr65> <a0,fr66> <a0,fr67> <a0,fr68> <a0,fr69> <a0,fr70> <a0,fr71>
<a0,fr72> <a0,fr73> <a0,fr74> <a0,fr75> <a0,fr76> <a0,fr77>
Runaway definition?
->\pgfsyssoftpath@movetotoken {0.0pt}{0.0pt}\pgfsyssoftpath@linetotoken \ETC.
! TeX capacity exceeded, sorry [main memory size=3000000].
\pgfsyssoftpath@thepath ...rtatoken {70.11478pt}{5
                                                  .69054pt}\pgfsyssoftpath@c...
l.470 \end{frame}
                 
Output written on main.pdf (33 pages).
SyncTeX written on main.synctex.gz.

Transcript written on main.log.

Sorry, but "MiKTeX Compiler Driver" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\xxxxxx\AppData\Local\MiKTeX\miktex\log\texify.log
```

**Comment by FvNCCR228** [comment]
> 好像还是不行，出现部分提示如下
> ```shell
> LaTeX Warning: Citation '_ugc_2018' on page 26 undefined on input line 9.
> 
> 
> LaTeX Warning: Citation '__2018' on page 26 undefined on input line 10.
> 
> )
> Overfull \hbox (13.1042pt too wide) in paragraph at lines 428--428
> [][][][]  
> 
> Overfull \hbox (1.03467pt too wide) has occurred while \output is active
>  [][]|  
> [26]
> No file main.toc.
> 
> Overfull \hbox (13.1042pt too wide) in paragraph at lines 433--433
> [][][][]  
> 
> Overfull \hbox (1.03467pt too wide) has occurred while \output is active
>  [][]|  
> [27] <a0,fr0> <a0,fr1> <a0,fr2> <a0,fr3> <a0,fr4> <a0,fr5> <a0,fr6> <a0,fr7>
> <a0,fr8> <a0,fr9> <a0,fr10> <a0,fr11> <a0,fr12> <a0,fr13> <a0,fr14> <a0,fr15>
> <a0,fr16> <a0,fr17> <a0,fr18> <a0,fr19> <a0,fr20> <a0,fr21> <a0,fr22>
> <a0,fr23> <a0,fr24> <a0,fr25> <a0,fr26> <a0,fr27> <a0,fr28> <a0,fr29>
> <a0,fr30> <a0,fr31> <a0,fr32> <a0,fr33> <a0,fr34> <a0,fr35> <a0,fr36>
> <a0,fr37> <a0,fr38> <a0,fr39> <a0,fr40> <a0,fr41> <a0,fr42> <a0,fr43>
> <a0,fr44> <a0,fr45> <a0,fr46> <a0,fr47> <a0,fr48> <a0,fr49> <a0,fr50>
> <a0,fr51> <a0,fr52> <a0,fr53> <a0,fr54> <a0,fr55> <a0,fr56> <a0,fr57>
> <a0,fr58> <a0,fr59> <a0,fr60> <a0,fr61> <a0,fr62> <a0,fr63> <a0,fr64>
> <a0,fr65> <a0,fr66> <a0,fr67> <a0,fr68> <a0,fr69> <a0,fr70> <a0,fr71>
> <a0,fr72> <a0,fr73> <a0,fr74> <a0,fr75> <a0,fr76> <a0,fr77>
> Runaway definition?
> ->\pgfsyssoftpath@movetotoken {0.0pt}{0.0pt}\pgfsyssoftpath@linetotoken \ETC.
> ! TeX capacity exceeded, sorry [main memory size=3000000].
> \pgfsyssoftpath@thepath ...rtatoken {70.11478pt}{5
>                                                   .69054pt}\pgfsyssoftpath@c...
> l.470 \end{frame}
>                  
> Output written on main.pdf (33 pages).
> SyncTeX written on main.synctex.gz.
> 
> Transcript written on main.log.
> 
> Sorry, but "MiKTeX Compiler Driver" did not succeed.
> 
> The log file hopefully contains the information to get MiKTeX going again:
> 
>   C:\Users\xxxxxx\AppData\Local\MiKTeX\miktex\log\texify.log
> ```

试着首先编译一下项目的main.tex，另外，您发的错误报告中前两项warning都是文章引用相关的

**Comment by FvNCCR228** [comment]
> 好像还是不行，出现部分提示如下
> ```shell
> LaTeX Warning: Citation '_ugc_2018' on page 26 undefined on input line 9.
> 
> 
> LaTeX Warning: Citation '__2018' on page 26 undefined on input line 10.
> 
> )
> Overfull \hbox (13.1042pt too wide) in paragraph at lines 428--428
> [][][][]  
> 
> Overfull \hbox (1.03467pt too wide) has occurred while \output is active
>  [][]|  
> [26]
> No file main.toc.
> 
> Overfull \hbox (13.1042pt too wide) in paragraph at lines 433--433
> [][][][]  
> 
> Overfull \hbox (1.03467pt too wide) has occurred while \output is active
>  [][]|  
> [27] <a0,fr0> <a0,fr1> <a0,fr2> <a0,fr3> <a0,fr4> <a0,fr5> <a0,fr6> <a0,fr7>
> <a0,fr8> <a0,fr9> <a0,fr10> <a0,fr11> <a0,fr12> <a0,fr13> <a0,fr14> <a0,fr15>
> <a0,fr16> <a0,fr17> <a0,fr18> <a0,fr19> <a0,fr20> <a0,fr21> <a0,fr22>
> <a0,fr23> <a0,fr24> <a0,fr25> <a0,fr26> <a0,fr27> <a0,fr28> <a0,fr29>
> <a0,fr30> <a0,fr31> <a0,fr32> <a0,fr33> <a0,fr34> <a0,fr35> <a0,fr36>
> <a0,fr37> <a0,fr38> <a0,fr39> <a0,fr40> <a0,fr41> <a0,fr42> <a0,fr43>
> <a0,fr44> <a0,fr45> <a0,fr46> <a0,fr47> <a0,fr48> <a0,fr49> <a0,fr50>
> <a0,fr51> <a0,fr52> <a0,fr53> <a0,fr54> <a0,fr55> <a0,fr56> <a0,fr57>
> <a0,fr58> <a0,fr59> <a0,fr60> <a0,fr61> <a0,fr62> <a0,fr63> <a0,fr64>
> <a0,fr65> <a0,fr66> <a0,fr67> <a0,fr68> <a0,fr69> <a0,fr70> <a0,fr71>
> <a0,fr72> <a0,fr73> <a0,fr74> <a0,fr75> <a0,fr76> <a0,fr77>
> Runaway definition?
> ->\pgfsyssoftpath@movetotoken {0.0pt}{0.0pt}\pgfsyssoftpath@linetotoken \ETC.
> ! TeX capacity exceeded, sorry [main memory size=3000000].
> \pgfsyssoftpath@thepath ...rtatoken {70.11478pt}{5
>                                                   .69054pt}\pgfsyssoftpath@c...
> l.470 \end{frame}
>                  
> Output written on main.pdf (33 pages).
> SyncTeX written on main.synctex.gz.
> 
> Transcript written on main.log.
> 
> Sorry, but "MiKTeX Compiler Driver" did not succeed.
> 
> The log file hopefully contains the information to get MiKTeX going again:
> 
>   C:\Users\xxxxxx\AppData\Local\MiKTeX\miktex\log\texify.log
> ```

这个感觉是 footfullcite 命令出问题了
确定一下是不是使用的biber编译参考文献

**Comment by Alafun** [comment]
> 确定一下是不是使用的biber编译参考文献

对，应该就是这个问题

因为是小白的缘故，TeXWorks 里面默认只有这些配置，没有和这个项目完全匹配的配置。

![image](https://user-images.githubusercontent.com/78416589/157433780-e7299786-9f47-4e5c-a86d-85a74fa8a5da.png)


所以就搜索了一下，最后按照[这个教程](https://bithesis.spencerwoo.com/Guide/2-Usage/Downloading-and-using-templates.html#:~:text=%E6%AF%94%E5%A6%82%EF%BC%8C%E7%BC%96%E8%AF%91%E4%B8%BB%E6%96%87%E6%A1%A3%E4%B8%BA%20main.tex%20%E7%9A%84%20LaTeX%20%E9%A1%B9%E7%9B%AE%EF%BC%8C%E6%88%91%E4%BB%AC%E5%85%B7%E4%BD%93%E7%9A%84%E5%91%BD%E4%BB%A4%E4%B8%BA%EF%BC%9A)，成功用xelatex+biber编译了

![圈出来的](https://user-images.githubusercontent.com/78416589/157433678-eaa176c4-c32e-48a6-b915-9ccf0afe8c87.png)

**Comment by FvNCCR228** [comment]
> 

找到问题了就可以了, 毕竟都是从小白一步步走过来的.

在了解的情况下问题的原因可以自己尝试分析 (建议先 Bing), 比如上面显示的:
```
LaTeX Warning: Citation '_ugc_2018' on page 26 undefined on input line 9.
```
其中 Citation 就是引用, undefined 表明该文献标签未定义, 说明可能 bib 文献数据库中无该文献条目或可能链接出错, 我便在这里猜测是文献库编译引擎使用错误 (大部分采用的是 BibTex 引擎 (很多编译器的默认设置), 本项目采用 Biber 引擎), 当然这需要使用者去看项目的说明文档, 我在其中就写明了引擎为 XeLaTeX + Biber.

所以, 记得看 manual, readme 之类的.

我马上要发布新版本了, 对页眉和页脚部分有极大改动, 谢谢支持哦.

另外VS Code建议用黑色主题, 眼睛看着更舒适.

**Comment by Alafun** [comment]
> > 
> 
> 找到问题了就可以了, 毕竟都是从小白一步步走过来的.
> 
> 在了解的情况下问题的原因可以自己尝试分析 (建议先 Bing), 比如上面显示的:
> 
> ```
> LaTeX Warning: Citation '_ugc_2018' on page 26 undefined on input line 9.
> ```
> 
> 其中 Citation 就是引用, undefined 表明该文献标签未定义, 说明可能 bib 文献数据库中无该文献条目或可能链接出错, 我便在这里猜测是文献库编译引擎使用错误 (大部分采用的是 BibTex 引擎 (很多编译器的默认设置), 本项目采用 Biber 引擎), 当然这需要使用者去看项目的说明文档, 我在其中就写明了引擎为 XeLaTeX + Biber.
> 
> 所以, 记得看 manual, readme 之类的.
> 
> 我马上要发布新版本了, 对页眉和页脚部分有极大改动, 谢谢支持哦.
> 
> 另外VS Code建议用黑色主题, 眼睛看着更舒适.

好的，好的。谢谢你呀 ！
