### ISSUE TITLE
theorem环境的复数

### ISSUE THREAD

**Issue by thinktown** [FvNCCR228/SCU_Beamer_Slide-demo#4]
作者好，很漂亮的模板！
请问自定义的```scu@theorem```中的```@pl```参数要怎么用呢，在同时有多个examples想要加个s，又不想额外定义新的环境

**Comment by FvNCCR228** [comment]
> 作者好，很漂亮的模板！
> 请问自定义的```scu@theorem```中的```@pl```参数要怎么用呢，在同时有多个examples想要加个s，又不想额外定义新的环境

这个是cleveref智能引用宏包引用名称定义用的。

具体使用在1190行。

比如两个区块，Source Code 1.1和Source Code 1.2。
标签分别为code:ex1，code:ex2。
引用时使用\vref{code:ex1,code:ex2}，那么将显示 source codes 1.1 and 1.2 on page xx

**Comment by FvNCCR228** [comment]
> 作者好，很漂亮的模板！
> 请问自定义的```scu@theorem```中的```@pl```参数要怎么用呢，在同时有多个examples想要加个s，又不想额外定义新的环境

不过我看字面意思，是想一个区块包含多个区块的内容吗，比如 Example 1.1-1.2？

**Comment by FvNCCR228** [comment]
> > 作者好，很漂亮的模板！
> > 请问自定义的```scu@theorem```中的```@pl```参数要怎么用呢，在同时有多个examples想要加个s，又不想额外定义新的环境
> 
> 不过我看字面意思，是想一个区块包含多个区块的内容吗，比如 Example 1.1-1.2？

如果是这样，区块环境真不好实现，只有自定义标题，环境用完后步进计数器

**Comment by thinktown** [comment]
@FvNCCR228 好的感谢，看来我之前是理解错了。另外请教一个小问题
我按照
```
\usepackage{varioref}
\usepackage{hyperref}
\usepackage{cleveref}
```
顺序调用宏包总是要报错
```
hyperref package loaded with implicit=false option - disabling cleveref's hyperref support. This situation is not supported by cleveref, and there's no guarantee anything will work. You're on your own!.

```

**Comment by FvNCCR228** [comment]
> 
> @FvNCCR228 好的感谢，看来我之前是理解错了。另外请教一个小问题
> 我按照
> ```
> \usepackage{varioref}
> \usepackage{hyperref}
> \usepackage{cleveref}
> ```
> 顺序调用宏包总是要报错
> ```
> hyperref package loaded with implicit=false option - disabling cleveref's hyperref support. This situation is not supported by cleveref, and there's no guarantee anything will work. You're on your own!.
> 
> ```
> 

hyperref宏包不用调用，beamer类调用过，重复调用会报错
